// with-element-plus/src/popup/App.vue
<script setup lang="ts">
import { ref } from 'vue';

const count = ref(0);
</script>

<template>
  <div class="content">
    <p>Count: {{ count }}</p>
    <el-button type="primary" @click="count++">Click me</el-button>
  </div>
</template>

<style scoped>
.content {
  text-align: center;
  padding: 12px;
}
</style>

// with-antd/src/popup/App.tsx
import { useState } from 'react';
import { Button } from 'antd';
import './App.css';

function App() {
  const [count, setCount] = useState(0);
  return (
    <div className="content">
      <p>Count: {count}</p>
      <Button type="primary" onClick={() => setCount(count + 1)}>
        Click me
      </Button>
    </div>
  );
}

export default App;
